In [1]:
import pandas as pd

In [2]:
def skip_rows(index):
    return index in [1, 2]

df = pd.read_csv("qualtrics_raw_data.csv", header=0, skiprows=skip_rows)

In [3]:
df.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q65_4,Q65_5,Q5,Q2.7,Q66,Q2.8,RecipientEmail.1,RecipientFirstName.1,RecipientLastName.1,Random ID
0,6/12/23 11:20,6/12/23 11:24,IP Address,205.175.106.149,100,210,True,6/12/23 11:24,R_1N2FgagYQnPoR9S,NaN,...,NaN,NaN,NaN,"Yes, I consent to continuing with this study.",NaN,dkjd@2.com,NaN,NaN,NaN,NaN
1,6/12/23 11:25,6/12/23 11:26,IP Address,73.97.212.176,3,58,False,6/19/23 11:26,R_vAMwaz9Ml2PbKF3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6/12/23 11:30,6/12/23 12:44,IP Address,205.175.106.119,88,4436,False,6/19/23 12:44,R_2S1YEzzz9yA6V3C,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6/12/23 11:16,6/12/23 13:01,IP Address,205.175.118.129,69,6284,False,6/19/23 13:01,R_3fcIcQ489pz8hC6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6/28/23 11:39,6/28/23 11:47,Survey Preview,NaN,100,475,True,6/28/23 11:47,R_2WZtKInAO7LHdv7,NaN,...,NaN,NaN,NaN,"Yes, I consent to continuing with this study.",NaN,roteml@uw.edu,NaN,NaN,NaN,NaN

In [4]:
email_list = {
    'p008': 'Samanthaadofo@gmail.com',
    'p015': 'biswast@bxscience.edu',
    'p018': 'kahssaydebora@gmail.com',
    'p055': 'matthewdemps01@gmail.con',
    'p076': 'asutsu564@gmail.com',
    'p079': 'halleyre2007@gmail.com',
    'p086': 'kaunglin445@gmail.com',
    'p088': 'tersoovictor3@gmail.com',
    'p089': 'zeyleasolomon@gmail.com',
    'p095': 'isaiah.knight4532@gmail.com',
    'p096': 'isaacbender2006@gmail.com',
    'p098': 'galeyeetoo@gmail.com',
    'p099': 'dogelife8@gmail.com',
    'p104': 'thatonechild28@gmail.com',
    'p108': 'freakyfriday1234567@gmail.com',
    'p111': 'nyxswagger@gmail.com',
    'p115': 'obedientecamila@gmail.com',
    'p118': 'iamablueberrymuffin6@gmail.com',
    'p120': 'tivedant@gmail.com',
    'p121': 'niveenmwahba@gmail.com',
    'p141': 'kentinez11@gmail.com',
    'p142': 'samikshaaprabhu.09@gmail.com',
    'p164': 'Itsaxelok@gmail.com',
    'p177': 'lukelehan58@gmail.com',
    'p188': 'Griffinsimmons61@gmail.com'
}

In [5]:
email_df = pd.DataFrame(list(email_list.items()), columns=['pid', 'Email'])

In [6]:
df_ = df[df['Q1.41'].apply(lambda x: x in email_list.values())].drop_duplicates(subset=['Q1.41'])
df_ = pd.merge(df_, email_df, left_on='Q1.41', right_on='Email')

In [13]:
export_column_list = [
    'pid',
    'Q1.2',
    'Q1.11',
    'Q29',
    'Q1.12',
    'Q1.13',
    'Q2.1_12',
    'Q2.1_13',
    'Q2.1.1'
]
filtered_column_list = [col for col in export_column_list if col in df_.columns]
df_subset = df_[filtered_column_list]

In [21]:
df_subset.to_csv('./demographics_export.csv')

In [ ]:
# Age
val = df_['Q1.2'].value_counts()
perc = df_['Q1.2'].value_counts(normalize=True) * 100
res = pd.DataFrame({
    'Counts': val, 
    'Percentage': perc
})
res

In [ ]:
pd.to_numeric(df_['Q1.2'], errors='coerce').describe()

In [ ]:
# Gender
val = df_['Q1.11'].value_counts()
perc = df_['Q1.11'].value_counts(normalize=True) * 100
res = pd.DataFrame({
    'Counts': val, 
    'Percentage': perc
})
res

In [ ]:
# Sexuality
val = df_['Q29'].value_counts()
perc = df_['Q29'].value_counts(normalize=True) * 100
res = pd.DataFrame({
    'Counts': val, 
    'Percentage': perc
})
res

In [ ]:
# Ethnicity
val = df_['Q1.12'].value_counts()
perc = df_['Q1.12'].value_counts(normalize=True) * 100
res = pd.DataFrame({
    'Counts': val, 
    'Percentage': perc
})
res

In [ ]:
pd.to_numeric(df_['Q2.1_12'], errors='coerce') * 60 + df_['Q2.1_12']

In [ ]:
(pd.to_numeric(df_['Q2.1_12'], errors='coerce') * 60 + df_['Q2.1_12']).describe()

In [ ]:
df_['Q2.1.1']

In [ ]:
# columns_to_convert = [
#     'Q3.7_1', 'Q3.7_2', 'Q3.7_3', 'Q3.8_1', 'Q3.8_2', 'Q3.8_3',
#     'Q4.1_1', 'Q4.1_2', 'Q4.1_3', 'Q4.1_4', 'Q4.12_1', 'Q4.12_2', 'Q4.12_3', 'Q4.12_4', 'Q4.12_5',
#     'Q4.2_1', 'Q4.2_2', 'Q4.2_3', 'Q4.2_4', 'Q65_1', 'Q65_2', 'Q65_3', 'Q65_4', 'Q65_5'
# ]

# # Apply the conversion only to the specified columns
# for column in columns_to_convert:
#     if column in df_.columns:  # Check if the column exists in the DataFrame to avoid KeyError
#         df_[column] = df_[column].apply(lambda x: int(x.split(' - ')[0]) if pd.notnull(x) and ' - ' in x else x)